### ISSUE TITLE
Allow concatenating of sources

### ISSUE THREAD

**Issue by Cuel** [seeden/mongoose-permalink#1]
Hi, at first I was expecting 'sources' to be concatenated before the permalink is created, but it exits after it finds a non-blank-value. Could concatenation be allowed aswell?

**Comment by seeden** [comment]
Hi 
I rewrote this plugin and added some tests. Please see a latest documentation.
I added option named operation for concat.

``` js
import mongoosePermalink, { Operation } from 'mongoose-permalink';

{
  sources: ['firstName', 'lastName'],
  operation: Operation.CONCAT
}
```

**Comment by Cuel** [comment]
Much appriciated!
